# 1

In [1]:
import numpy as np

a = np.random.randint(0, 100, size=(10))

print(a)
print(a.dtype)

[17 45 76 48 58 35 29 63 26 81]
int32


# 2

In [11]:
import numpy as np

mat = np.random.rand(5,5)

print(mat, "\n")
print(mat.min(), "\n")
print(mat.max())

[[0.34787559 0.82739789 0.07303109 0.71610724 0.59875526]
 [0.1828091  0.03198176 0.95752723 0.12642219 0.61596037]
 [0.6689364  0.25189019 0.87169983 0.79262069 0.66807114]
 [0.78202762 0.17842458 0.6185604  0.32383795 0.67502059]
 [0.24982703 0.49776427 0.67630695 0.47885308 0.1047271 ]] 

0.03198175561075567 

0.9575272266893602


# 3

In [15]:
arr = np.random.rand(10)

arr_int = (arr * 10).astype(int)

print(arr)
print(arr_int)


[0.15989694 0.42785054 0.60426164 0.36287619 0.50438177 0.36618449
 0.47985427 0.30949179 0.63307011 0.76458743]
[1 4 6 3 5 3 4 3 6 7]


# 4

In [21]:
matriz = np.random.randint(0,10, (3,3))

matriz[1, :] = -1
print(f"ALterada segunda linha para -1: \n {matriz}")

ALterada segunda linha para -1: 
 [[ 8  2  2]
 [-1 -1 -1]
 [ 9  6  8]]


# 5

In [2]:
import pandas as pd

mat = np.array([["Banana", 7.90, 12], ["Maça", 10.20, 4], ["Pera", 11.80, 4]])

df = pd.DataFrame(mat, columns=['Fruta', 'Preço', 'Qtde'])
df

Fruta Preço Qtde
0  Banana   7.9   12
1    Maça  10.2    4
2    Pera  11.8    4

# 5

In [18]:
import pandas as pd

df = pd.DataFrame([["Banana", 7.90, 12], ["Maça", 10.20, 4], ["Pera", 11.80, 4]], columns=['Fruta', 'Preço', 'Qtde'])
df

Fruta  Preço  Qtde
0  Banana    7.9    12
1    Maça   10.2     4
2    Pera   11.8     4